-
  name: dotfiles
  working_directory: /home/rolfie/Documents/dotfiles
  enter_command: nvim
  window_name: vim
  windows:
    - name: config
      session_name: dotfiles
      working_directory: /home/rolfie/\.config
-
  name: cv
  working_directory: /media/rolfie/ssd2/docs/cv
  enter_command: nvim
  window_name: vim
  windows:
    - name: bash
      session_name: cv
      working_directory: /media/rolfie/ssd2/docs/cv
-
  name: aoc
  working_directory: /media/rolfie/ssd2/projects/aoc
  enter_command: nvim
  window_name: vim
  windows:
    - name: term
      session_name: aoc
      working_directory: /media/rolfie/ssd2/projects/aoc
      command: nu
-
  name: tmux_creator
  working_directory: /media/rolfie/ssd2/projects/tmux-creator
  enter_command: nvim
  window_name: vim
  windows:
    - name: rust
      session_name: tmux_creator
      working_directory: /media/rolfie/ssd2/projects/tmux-creator
    - name: log
      session_name: tmux_creator
      working_directory: /media/rolfie/ssd2/projects/tmux-creator
-
  name: mini_games
  working_directory: /media/rolfie/ssd2/projects/mini_games
  enter_command: nvim
  window_name: vim
  windows:
    - name: rust
      session_name: mini_games
      working_directory: /media/rolfie/ssd2/projects/mini_games
-
  name: stratego
  working_directory: /media/rolfie/ssd2/projects/cours/m1/stratego
  enter_command: nvim
  window_name: vim
  windows:
    - name: rust
      session_name: stratego
      working_directory: /media/rolfie/ssd2/projects/cours/m1/stratego
-
  name: ffvelo_api
  working_directory: /media/rolfie/ssd2/projects/ffvelo/generation2024
  enter_command: nvim
  window_name: vim
  windows:
    - name: bash
      session_name: ffvelo_api
      working_directory: /media/rolfie/ssd2/projects/ffvelo/generation2024
    - name: docker
      session_name: ffvelo_api
      working_directory: /media/rolfie/ssd2/projects/ffvelo/generation2024
-
  name: rust_lessons
  working_directory: /media/rolfie/ssd2/projects/cours/rust
  enter_command: nvim
  window_name: vim
  windows:
    - name: bash
      session_name: rust_lessons
      working_directory: /media/rolfie/ssd2/projects/cours/rust
-
  name: train_simulator
  working_directory: /media/rolfie/ssd2/projects/train_simulator
  enter_command: nvim
  window_name: vim
  windows:
    - name: bash
      session_name: train_simulator
      working_directory: /media/rolfie/ssd2/projects/train_simulator
-
  name: dex_map
  working_directory: /media/rolfie/ssd2/projects/dex_map
  enter_command: nvim
  window_name: vim
  windows:
    - name: bash
      session_name: dex_map
      working_directory: /media/rolfie/ssd2/projects/dex_map
-
  name: socials
  working_directory: /media/rolfie/ssd2/projects/socials
  enter_command: nvim
  window_name: vim
  windows:
    - name: nu
      session_name: socials
      working_directory: /media/rolfie/ssd2/projects/socials
      command: nu
