# theme = "gruvbox-dark"
# icons = "material"
[theme]
theme = "plain"

[icons]
icons = "none"

# [[block]]
# block = "docker"
# interval = 2
# format = "{running}/{total}"

[[block]]
block = "hueshift"
hue_shifter = "redshift"
step = 50
click_temp = 3500


# [[block]]
# block = "nvidia_gpu"
# interval = 1
# format = "GT 1030 $utilization $temperature $clocks"

[[block]]
block = "load"
format = "1m:$1m 5m:$5m"
interval = 1

[[block]]
block = "cpu"
interval = 1
format = "$barchart.str() $utilization.eng() $frequency.eng()"

# [[block]]
# block = "memory"
# clickable = false
# interval = 30
# warning_mem = 70
# critical_mem = 90

[[block]]
block = "battery"
interval = 10
format = "$percentage $time"

[[block]]
block = "sound"
format = "$volume"

[[block]]
block = "keyboard_layout"
driver = "setxkbmap"
interval = 15

[[block]]
block = "time"
interval = 60
locale = "fr_FR"
[block.format]
full = "%d/%m %R"
short = "%R"

