if [ -f ~/.config/shell/common/aliases ]; then
  source ~/.config/shell/common/aliases
fi

alias cours='function _(){ cd /media/rolfie/ssd2/projects/cours/$1; }; _'
alias dev='function _(){ cd /media/rolfie/ssd2/projects/$1; }; _'

